name: drpy
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - proplot
  - xarray
  - netcdf4
  - pyyaml
  - pandas
  - pyproj
  - cartopy
  - pip
  - h5py
  - ipykernel
  - dask
