name: drpy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10  # Adjust based on your needs
  - numpy
  - scipy
  - matplotlib
  - proplot
  - xarray
  - netcdf4
  - pyyaml
  - pandas
  - pyproj
  - cartopy
  - pip
  - h5py
  - ipykernel
  - dask
